### ISSUE TITLE
Lead time for event

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#175]
From Catalina:

> Forecast data: maybe we can be more explicit: A flood is expected in X number of days/leadtime.
I think the functionality of having the historical floods is very nice, but it should not be the main feature. Could we have a more flashy sign that says: Current forecasted flood event, to make sure they don’t get confused with any other previous floods events.

Can we do this by adding two rows to the summary table:

Event status: Current (with other option being Historical)
Lead time: 7 days

<img width="419" alt="image" src="https://user-images.githubusercontent.com/178003/70412021-9e5d3780-1a4b-11ea-8dcd-cd057e465a19.png">

Then we can probably remove the Acquisition date row as Cataline suggests.

**Comment by lucernae** [comment]
> Then we can probably remove the Acquisition date row as Cataline suggests.

Yes @timlinux  I do agree with Catalina here. In fact it was actually bugging me before. In other forecast, they all based on lead time.
The acquisition_date is still needed for the database (we need it to filter which one is current forecast). But we won't show it from the UI because it is equivalent to Lead time.
Lead time can be taken from `forecast_date - acquisition_date`.
For the forecast fetch itself to the front end, I already based it using lead time for current forecast.
For historical forecast, I choose to show in the calendar, the least lead time available for that day. Because that would be the most recent forecast for that given date.

What I Imagine can be an improvement later is:
- For historical forecast (if we click date in the past), we should list all forecast that was made for that given date. So I imagine it would be a list of forecast events with increasing lead time (from the most recent to the oldest). So if people want to drill down and see the history of the forecast and trigger status in the same date, it would be possible.
