### ISSUE TITLE
Calendar preview of flood events and Database are not always in sync

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/fbf-project#202]
# Problem

Besided the time issue that we discussed earlier on with @lucernae It still seems that some events are not visible on the calendar even though they have been successfully been updated in the Database.

![fetch-updates](https://user-images.githubusercontent.com/2510900/71180254-74d9b280-227a-11ea-8054-2af56a7cef42.png)

This is the calendar preview
![calednar](https://user-images.githubusercontent.com/2510900/71180294-89b64600-227a-11ea-9da2-9a792876d784.png)

**Comment by lucernae** [comment]
The frontend now behaves for live/current forecast only.
For forecast dates greater than today, the calendar now only shows current forecast, which is the forecast made today (acquisition_date today), for the future (forecast_date greater than today).

If your forecast_date is in the future and you want to show it in the calendar, the acquisition_date needs to be today. This is because we don't have drill down mechanism for browsing different forecast in the same date (from previous acquisition_date).

If you want to upload flood event just to check the flood map and summaries, you can upload it into forecast_date in the past, and acquisition_date in the past (so it became historical forecast).
For historical forecast, at the moment, we only shows the least lead_time available in the same forecast_date. Again, this is because we don't have drill down mechanism yet for browsing past forecast in the same date.

There is also a bug involved with calculating lead time, related with this issue, but I fixed it recently after discussing it with @NyakudyaA :
https://github.com/kartoza/fbf-project/pull/200/files.

So, I think we can close this one.
