### ISSUE TITLE
Use single table for handling uploads and draw functionality

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/fbf-project#75]
# problem

Currently, the draw functionality is using the table `flood` in the database and the upload form is using the `flooded_area`

We need both methods to use the same table so that we can have views or triggers populating the same tables

**Comment by lucernae** [comment]
I propose that we replace all the logic for draw flood to use `flood_map` and `flood_event` in the future. But that is low priority since we already have upload functionality working.
@NyakudyaA , I think we can just focus on using `flooded_area` as views to triggers all backend calculations/cache.

So, my idea is: for each `flood_event` we can get all associated `flooded_area`.
This geometries (for a single `flood_event` entry) needs to be returned back to the frontend, either via GeoJSON result or Geoserver so we can draw it in the map.
Additionally since there are multiple geometries in an event now, the statistics calculations might be heavy in the frontend, we might have to calculate it/cache the result in the backend.
The front end will just receive the result.
We need to discuss does everyone have the same picture with this approach.
CC @ann26 @NyakudyaA @timlinux . 
Please comment if there are any doubt.

**Comment by NyakudyaA** [comment]
@lucernae as long as the draw functionality exists on the dashboard it will not be a low priority because if a user draws a flood polygon they would expect to get the same statistics as the ones for upload functionality. 

The implications for that are that they might be two procedures in the DB which is not what we expect.

So either
* Fix to use the same layers or
* Disable for the draw functionality.

For any layers that are to be rendered in the front end, we should use GeoServer as much as possible and use cql_filters for filtering. I have already supplied @ann26 with the layers she has been requesting.

All the statistics are to be calculated in the backend using triggers and materialized views. So for any initial flood that is uploaded the data might not be instant but subsequent revisit will see the data cached
